### ISSUE TITLE
After a night open, network tab was stuck on an old block

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#134] opened 2015-05-23 07:36 UTC
Here is a screenshot after restart of cutecoin (which solved the issue):

![image](https://cloud.githubusercontent.com/assets/969136/7782934/08e060cc-012f-11e5-8221-0f915e7eff82.png)

It was stuck on block 15876.

**Comment by M5oul** [comment] 2015-05-23 12:16
Same issue on my side.

**Comment by Insoleet** [comment] 2015-05-24 22:05
Same block ?

**Comment by M5oul** [comment] 2015-05-24 22:51
I can't remember. It happends to me a secound time.

**Comment by Insoleet** [comment] 2015-05-25 06:12
As I need more infos, I'll let this bug opened. But since I plan to totally refator the network module, maybe it will disapear for 0.11.

**Comment by Insoleet** [comment] 2015-05-27 06:39
Probably duplicate of 
https://github.com/ucoin-io/cutecoin/commit/408e8aa3689bc249e1829a58e1177689738a8bb0

**Comment by Insoleet** [comment] 2015-05-27 06:40
Probably same problem as #137

**Closed** 2015-11-20 08:52 UTC
Labels: bug, wontfix
