### ISSUE TITLE
WoT does not show some certifications

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#248] opened 2015-11-09 10:56 UTC
For example: http://metab.ucoin.io/wot/lookup/galuel

This gives us 5 certifications, however cutecoin will show only the lasts 2. uCoin sends 5 certifications because all these are still valid and *have been* or *may be* added to the blockchain (according to `sigValidity` parameter of [UCP](https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#protocol-parameters)).

What is the algorithm in Cutecoinfor displaying certifications under /wot/lookup?

**Comment by Insoleet** [comment] 2015-11-09 11:13
The problem is the condition here : https://github.com/ucoin-io/cutecoin/blob/dev/src/cutecoin/core/registry/identity.py#L298

It's too simple. We have to check if the certifications in the lookup corresponds to the certification in certifiers-of, in which case we ignore it. If it does not corresponds to any certifications in certifiers-of, we add it.

**Comment by Insoleet** [comment] 2015-11-10 07:31
So the problem is about certification being expired.

I'm using the following test : 
```
current_block_mediantime - cert_time > parameters['sigValidity']
```

If it's True, the certification expired.

I don't see anything wrong with it ?!

**Comment by Insoleet** [comment] 2015-11-20 07:13
It seems that the problem is fixed with latest fixes in identities classes.

**Closed by Insoleet** 2015-11-20 07:13 UTC
Labels: bug
