### ISSUE TITLE
Transaction done twice when revive a not passed transaction

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#118] opened 2015-04-28 20:02 UTC
I made a transaction. This transaction was not accepted by the node; displayed in red. I revive the transaction. After validation, I saw two transactions done as you could see on the image bellow at two different dates:
![capture d ecran de 2015-04-28 21 52 32](https://cloud.githubusercontent.com/assets/4758871/7379036/1a9d0cb6-edf2-11e4-8805-1aa524d17dd2.png)

**Comment by Insoleet** [comment] 2015-04-30 07:04
Some questions : 
 - Did the transaction go red after some time ?
 - Did it go red because you were disconnected and no node was available ?

**Comment by M5oul** [comment] 2015-04-30 11:10
* The transaction became red the next time I opened CuteCoin. Almost 1 day.
* Do you mean I were disconnected during the transaction? I think I were well connected. Afterthought, I were well connected.

**Comment by Insoleet** [comment] 2015-04-30 13:15
Ok this is rather weird.

A transaction becomes red when it cannot be found in 15 blocks following the transfer action.

This would mean that the transaction was not validated during 15 blocks, but was later on ?

@c-geek , what's your opinion about this ?

**Comment by yvgithub** [comment] 2015-04-30 16:16
I don't know if it's the same bug but I have a lot of red transactions in cutecoin 0.9 and they become black in cutecoin 0.9.1.

**Comment by Insoleet** [comment] 2015-04-30 16:33
Well at the moments  the nodes are down, transactions cannot be validated.

**Comment by Insoleet** [comment] 2015-05-03 17:37
This may be linked to current bugs with cgeek nodes. Let's see if we can reproduce this bug in the time to come, after cgeek fixed the bugs on his side.

**Comment by Insoleet** [comment] 2015-05-06 17:12
Ok this was probably because of wrong behaviour after loading since 0.9.1.
https://github.com/ucoin-io/cutecoin/issues/120
FIxed in 0.9.2.

**Closed by Insoleet** 2015-05-06 17:12 UTC
Labels: bug
