### ISSUE TITLE
Bugs #2

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#220] opened 2015-09-20 15:26 UTC
![du_missing](https://cloud.githubusercontent.com/assets/4758871/9981400/3ebe308e-5fbc-11e5-8d69-330b04e9a888.png)

I have some UD missing for 18 and 19 september. I were member during this period.
This could come from the new network or from transactions in between.
That strange to see my last UD in italic.

**Comment by M5oul** [comment] 2015-09-20 15:36
It would be great if in network tab, nodes could be by default decreasing sorted on block numbers.

**Comment by M5oul** [comment] 2015-09-20 15:50
It would be great to add yellow color on network tab for nodes far, for instance, 10 blocks, from the upper blocks number, then orange for more than 10 blocks.

**Comment by Insoleet** [comment] 2015-09-20 17:11
DU in italic are because they are not validated yet. There needs to be [median fork window] blocks mined since the DU to be sure you received it.

Why not for nodes decreasing sorted on block numbers...

For the colors I don't see how that make sense from a client point of view. We only look at synced, unsynced and offline nodes...

**Comment by M5oul** [comment] 2015-09-21 09:13
Cutecoin crash alone with the desyncronized network of today:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/network.py", line 40, in lessThan
    return (left_data < right_data)
TypeError: unorderable types: int() < str()
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/network.py", line 40, in lessThan
    return (left_data < right_data)
TypeError: unorderable types: int() < str()
```

**Comment by Insoleet** [comment] 2015-09-21 12:12
Mmmh there is probably a wrong data sent in the fields of the nodes. Can you copy paste your file "meta_brouzouf_network" of your cache ?

**Comment by M5oul** [comment] 2015-09-21 17:18
https://moul.re/zerobin/?e3fcf91c19ddcea1#TvvvqyyNY1IxUOdoLjxPbDP0eeSp6OBbzyJCtxB36fw=

**Comment by Insoleet** [comment] 2015-09-23 10:48
Well I could not reproduce this bug... I'll close it for now, should not happen anymore when we start to check every data received by ucoin nodes ( Planned for 0.12 )

**Closed by Insoleet** 2015-09-23 10:48 UTC
Labels: bug, enhancement
